-- Script to create retail_clients table
-- This table was missing from the initial setup but is required by the Clientes Management component.

CREATE TABLE IF NOT EXISTS public.retail_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    dni_cuit TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    province TEXT,
    zip_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.retail_clients ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access (adjust as needed for production)
-- For now, allowing public access or authenticated access depending on your auth setup
-- Assuming similar to wholesale_clients where we might want authenticated access
CREATE POLICY "Enable all for authenticated users" ON public.retail_clients
    FOR ALL USING (true); -- 'true' allows everyone if RLS is enabled, useful for dev. 
                          -- In production change to: auth.role() = 'authenticated'

-- Create index for faster searches
CREATE INDEX IF NOT EXISTS idx_retail_clients_dni_cuit ON public.retail_clients(dni_cuit);
CREATE INDEX IF NOT EXISTS idx_retail_clients_name ON public.retail_clients(name);
