-- Tabla para Lista de Precios a Publicar
CREATE TABLE IF NOT EXISTS public.inventory_public (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL, -- Precio de publicación
  platform TEXT, -- MercadoLibre, Web, etc.
  status TEXT DEFAULT 'active', -- active, paused
  stock INTEGER DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by BIGINT REFERENCES public.users(id),
  updated_by BIGINT REFERENCES public.users(id)
);

-- Tabla para Ventas Mayoristas (Inventario específico)
CREATE TABLE IF NOT EXISTS public.inventory_wholesale (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL,
  description TEXT NOT NULL,
  wholesale_price DECIMAL(10, 2) NOT NULL,
  quantity INTEGER DEFAULT 0,
  min_quantity INTEGER DEFAULT 1, -- Cantidad mínima para precio mayorista
  category TEXT,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by BIGINT REFERENCES public.users(id),
  updated_by BIGINT REFERENCES public.users(id)
);

-- Habilitar RLS
ALTER TABLE public.inventory_public ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_wholesale ENABLE ROW LEVEL SECURITY;

-- Políticas (simplificadas para permitir acceso a autenticados)
CREATE POLICY "Enable all for authenticated users" ON public.inventory_public
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Enable all for authenticated users" ON public.inventory_wholesale
    FOR ALL USING (auth.role() = 'authenticated');
