-- Script COMPLETO para corregir base de datos (Usuarios e Inventario)
-- Ejecuta este script en el Editor SQL de Supabase para solucionar todos los errores reportados

-- 1. Corregir esquema de tabla 'users' (Soluciona error PGRST204 y botón "Dar" mayoristas)
DO $$
BEGIN
    -- Agregar created_by
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'created_by') THEN
        ALTER TABLE users ADD COLUMN created_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
    END IF;

    -- Agregar updated_by
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'updated_by') THEN
        ALTER TABLE users ADD COLUMN updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
    END IF;

    -- Agregar can_view_wholesale
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'can_view_wholesale') THEN
        ALTER TABLE users ADD COLUMN can_view_wholesale BOOLEAN DEFAULT false;
    END IF;
END $$;

-- 2. Asegurar esquema de tabla 'inventory' (Inventario Principal)
DO $$
BEGIN
    -- Agregar created_by si falta
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inventory' AND column_name = 'created_by') THEN
        ALTER TABLE inventory ADD COLUMN created_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
    END IF;
    
    -- Agregar updated_by si falta
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inventory' AND column_name = 'updated_by') THEN
        ALTER TABLE inventory ADD COLUMN updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 3. Crear tablas independientes para Publicar y Mayoristas (Soluciona duplicación de datos)
CREATE TABLE IF NOT EXISTS public.inventory_public (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  platform TEXT,
  status TEXT DEFAULT 'active',
  stock INTEGER DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.inventory_wholesale (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL,
  description TEXT NOT NULL,
  wholesale_price DECIMAL(10, 2) NOT NULL,
  quantity INTEGER DEFAULT 0,
  min_quantity INTEGER DEFAULT 1,
  category TEXT,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL
);

-- 4. Habilitar seguridad (RLS) y políticas
ALTER TABLE public.inventory_public ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_wholesale ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_public' AND policyname = 'Enable all for authenticated users') THEN
        CREATE POLICY "Enable all for authenticated users" ON public.inventory_public FOR ALL USING (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_wholesale' AND policyname = 'Enable all for authenticated users') THEN
        CREATE POLICY "Enable all for authenticated users" ON public.inventory_wholesale FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 5. Recargar caché de esquema (CRUCIAL para que los cambios surtan efecto)
NOTIFY pgrst, 'reload schema';
