-- Script to setup and update Wholesale Management Tables

-- 1. Create or update wholesale_clients table
CREATE TABLE IF NOT EXISTS public.wholesale_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    business_name TEXT NOT NULL,
    cuit TEXT NOT NULL,
    address TEXT,
    province TEXT,
    city TEXT, -- New field
    contact_person TEXT,
    email TEXT,
    whatsapp TEXT,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add city column if it doesn't exist (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'wholesale_clients' AND column_name = 'city') THEN
        ALTER TABLE public.wholesale_clients ADD COLUMN city TEXT;
    END IF;
END $$;

-- 2. Create or update wholesale_orders table
CREATE TABLE IF NOT EXISTS public.wholesale_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT REFERENCES public.wholesale_clients(id) ON DELETE CASCADE,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT CHECK (status IN ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')) DEFAULT 'pending',
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create or update wholesale_order_items table
CREATE TABLE IF NOT EXISTS public.wholesale_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.wholesale_orders(id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    description TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0
);

-- 4. Create config table for wholesale percentages if not exists
CREATE TABLE IF NOT EXISTS public.config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iva_percentage NUMERIC DEFAULT 21,
    wholesale_percentage_1 NUMERIC DEFAULT 10,
    wholesale_percentage_2 NUMERIC DEFAULT 17,
    wholesale_percentage_3 NUMERIC DEFAULT 25,
    cuotas_3_percentage NUMERIC DEFAULT 20,
    cuotas_6_percentage NUMERIC DEFAULT 40,
    cuotas_9_percentage NUMERIC DEFAULT 60,
    cuotas_12_percentage NUMERIC DEFAULT 80
);

-- Insert default config if not exists
INSERT INTO public.config (id, iva_percentage, wholesale_percentage_1, wholesale_percentage_2, wholesale_percentage_3)
SELECT 1, 21, 10, 17, 25
WHERE NOT EXISTS (SELECT 1 FROM public.config WHERE id = 1);

-- 5. Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE public.wholesale_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wholesale_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wholesale_order_items ENABLE ROW LEVEL SECURITY;

-- Create policies (simplified for now - allow all authenticated users)
CREATE POLICY "Allow all operations for authenticated users on clients" ON public.wholesale_clients
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow all operations for authenticated users on orders" ON public.wholesale_orders
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow all operations for authenticated users on order items" ON public.wholesale_order_items
    FOR ALL USING (auth.role() = 'authenticated');

-- 6. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_wholesale_orders_client_id ON public.wholesale_orders(client_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_order_items_order_id ON public.wholesale_order_items(order_id);
